# Generated by Django 5.2 on 2025-04-12 09:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=35)),
                ('city_image', models.ImageField(upload_to='city_images')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(55)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('country_user', models.CharField(blank=True, max_length=32, null=True)),
                ('role_status', models.CharField(choices=[('client', 'client'), ('owner', 'owner')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, unique=True)),
                ('hotel_name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('hotel_name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('hotel_year', models.DateTimeField(auto_now_add=True)),
                ('hotel_description', models.TextField()),
                ('hotel_description_en', models.TextField(null=True)),
                ('hotel_description_ru', models.TextField(null=True)),
                ('hotel_stars', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address_en', models.CharField(max_length=50, null=True)),
                ('address_ru', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hotel_video', models.FileField(upload_to='videos')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_image', models.ImageField(upload_to='hotel_image')),
                ('hotel_video', models.FileField(upload_to='hotel_video')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='site_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('room_status', models.CharField(choices=[('vip', 'vip'), ('стандарт', 'стандарт'), ('двухместный', 'двухместный'), ('семейный', 'семейный')], max_length=100)),
                ('room_type', models.CharField(choices=[('свободен', 'свободен'), ('занят', 'занят'), ('ожидание', 'ожидание'), ('бронь', 'бронь')], default='свободен', max_length=100)),
                ('room_price', models.PositiveSmallIntegerField()),
                ('room_description', models.TextField()),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.hotel')),
                ('hotel_room_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.hotel')),
                ('hotel_room_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('подтверждено', 'подтверждено'), ('отменено', 'отменено'), ('ожидание', 'ожидание')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.hotel')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='room_image')),
                ('room_video', models.FileField(upload_to='room_video')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.room')),
            ],
        ),
    ]
